---

- name: "ensure User {{item.value.vuser}} exists"
  user:
    name: "{{item.value.vuser}}"
    comment: "virtual User for {{item.key}}"
    uid: "{{ item.value.vuser | regex_replace('^\\D*', '') }}"
    home: "/var/www/{{item.value.vuser}}"

- name: "create base directories for User {{item.value.vuser}}"
  file: 
    path: "/var/www/{{item.value.vuser}}/{{bd_item.key}}"
    owner: "{{item.value.vuser}}"
    group: "{{item.value.vuser}}"
    mode: "0755"
    state: "directory"
  with_dict: "{{ vuser_base_dirs }}"
  loop_control:
    loop_var: bd_item
 
- name: 
  template:
    src: "templates/vhost.conf.j2"
    dest: "/etc/httpd/sites-enabled/bitcoinrig.de.conf"
