---
# tasks file for chrnie.apache-vhost-suphp-letsencrypt

- name: install packages
  yum: 
    name: "{{item.key}}"
    state: "{%if item.value.state is defined %}{{ item.value.state }}{% else %}present{% endif %}"
  with_dict: "{{ avsl_packages }}"

- name: copy httpd basic config
  copy:
    src: files/etc_httpd/{{item}}
    dest: /etc/httpd/{{item}}
    owner: root
    group: root
    mode: "0644"
  with_items:
    - "./conf/httpd.conf"
    - "./conf.d/ssl.conf"
    - "./conf.d/welcome.conf"
    - "./conf.d/security.conf"

- name: "Create httpd site directories in the debian way"
  file: 
    path: "/etc/httpd/{{item}}"
    owner: root
    group: root
    mode: "0755"
    state: "directory"
  with_items: 
    - sites-available
    - sites-enabled

- name: Install suPHP
  include_tasks: suphp.yml

- name: Create vHosts and Users
  include_tasks: addVhost.yml
  with_dict: "{{avsl_vhosts}}"
  when: "avsl_vhosts is defined"
